export const authConstants = {
  GET_PROFILE_DATA_SUCCESS: "GET_PROFILE_DATA_SUCCESS",
  GET_PROFILE_DATA_FAILURE: "GET_PROFILE_DATA_FAILURE",
};
export const chatConstants = {
  GET_CHATS_SUCCESS: "GET_CHATS_SUCCESS",
  GET_CHATS_FAILURE: "GET_CHATS_FAILURE",
  ADD_NEW_CHAT_SUCCESS: "ADD_NEW_CHAT_SUCCESS",
  ADD_NEW_CHAT_FAILURE: "ADD_NEW_CHAT_FAILURE",
};
export const messageConstants = {
  GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
  GET_MESSAGE_FAILURE: "GET_MESSAGE_FAILURE",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",
  GET_A_NEW_MESSAGE_SUCCESS: "GET_A_NEW_MESSAGE_SUCCESS",
  GET_A_NEW_MESSAGE_FAILURE: "GET_A_NEW_MESSAGE_FAILURE",
};
